// This file is generated by icon spritesheet generator

export const iconNames = [
	'x',
	'sun',
	'moon',
	'menu',
	'loader-circle',
	'laptop',
	'globe',
	'circle',
	'chevrons-down',
	'chevron-right',
	'chevron-down',
	'check',
	'arrow-left',
] as const

export type IconName = (typeof iconNames)[number]
