name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
env:
  OP_ENV: development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-22.04
    # only build/deploy branches on pushes and PRs
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Set OP_ENV
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "OP_ENV=production" >> $GITHUB_ENV
          else
            echo "OP_ENV=development" >> $GITHUB_ENV
          fi

      - name: Print OP_ENV
        run: echo $OP_ENV

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '50'

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: ⚙️ Install 1password CLI
        uses: 1password/load-secrets-action/configure@v2
        with:
          # Persist the 1Password Service Account Authorization token
          # for next steps.
          # Keep in mind that every single step in the job is now able
          # to access the token.
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: 🔑 Load environment variables
        id: op_secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          FLY_API_TOKEN: op://${{ env.OP_ENV }}/FLY/FLY_API_TOKEN
          SENTRY_AUTH_TOKEN: op://${{ env.OP_ENV }}/SENTRY/SENTRY_AUTH_TOKEN

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: 🚀 Deploy Staging 🚧
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          flyctl deploy --remote-only \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          --build-arg OP_ENV=${{ env.OP_ENV }} \
          --build-arg OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} \
          --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
          --app ${{ steps.app_name.outputs.value }}-staging
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}

      - name: 🚀 Deploy Production 🚀
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          flyctl deploy --remote-only \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          --build-arg OP_ENV=${{ env.OP_ENV }} \
          --build-arg OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} \
          --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}
